alias addalias='nano ~/.bash_aliases'
alias n="neofetch --ascii_distro"
alias c="clear"
alias sus='systemctl suspend'
alias editconfig='nano ~/.zshrc'
alias horny="ssh -X cosmicelijah@68.50.117.190 feh -FZzx -D 5 /home/cosmicelijah/Documents/hentai-repo/straight"
alias startgnome='gnome-shell --wayland'
alias sshhentaiguy76='ssh -X hentaiguy76@99.6.161.34'
alias header="nano ~/.bash_header"
alias start="source ~/.zshrc"
alias manjaroserver="ssh -X cosmicelijah@68.50.117.190"
# alias "updatewebsite"="ssh cosmicelijah@10.0.0.184 'rm -r ~/website/wibsite && sshpass -p Coconut2003! scp -r cosmicelijah@6.50.117.190:~/Documents/website/ ~/website/wibsite/ && doas systemctl restart website && echo Done"
alias elephant="repo-elephant -h && repo-elephant"
alias bashtop=bpytop
alias pycharm="screen -dmS pycharm"
# alias neofetch=hentaifetch
alias localhorny="feh -FZzx -D 5 ~/Documents/stuff/"
alias count="python ~/word_count.py"
alias cdfp="cd /home/CosmicElijah/EclipseProjects/csse220-winter-2021-2022-final-project-w22_r_503"
alias gitp="git push -u origin master"
alias gitf="git pull origin"
