alias addalias='nano ~/.bash_aliases'
alias n="neofetch"
alias c="clear"
alias sus='systemctl suspend'
alias editconfig='nano ~/.zshrc'
alias horny="ssh -X cosmicelijah@68.50.117.190 feh -FZzx -D 5 /home/cosmicelijah/Documents/hentai-repo/straight"
alias startgnome='gnome-shell --wayland'
alias sshhentaiguy76='ssh -X hentaiguy76@99.6.161.34'
alias header="nano ~/.bash_header"
alias start="source ~/.zshrc"
alias manjaroserver="ssh -X cosmicelijah@68.50.117.190"
# alias "updatewebsite"="ssh cosmicelijah@10.0.0.184 'rm -r ~/website/wibsite && sshpass -p Coconut2003! scp -r cosmicelijah@6.50.117.190:~/Documents/website/ ~/website/wibsite/ && doas systemctl restart website && echo Done"
alias elephant="repo-elephant -h && repo-elephant"
alias bashtop=bpytop
alias cd="cd && ls"